# Generated by Django 2.2.5 on 2019-10-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mostwanted',
        ),
    ]
