# Generated by Django 2.2.5 on 2019-10-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0002_delete_mostwanted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mostwanted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('height', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=20)),
                ('crime_type', models.CharField(max_length=20)),
                ('crime_area', models.CharField(max_length=20)),
                ('victim', models.CharField(max_length=20)),
                ('crime_spot', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='pic')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
